# Generated by Django 4.0.2 on 2022-02-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
